// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMyHaGZ6NUoJU9qRFeoauuuGfsUOjQkLs',
    appId: '1:1050796442178:android:1e8af08751867352fe63db',
    messagingSenderId: '1050796442178',
    projectId: 'flutter-trivia-ex',
    storageBucket: 'flutter-trivia-ex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV-rCoTfVNRDyQ7h4kTiae-vKXLDn2-Wo',
    appId: '1:1050796442178:ios:f1dc36eb863e9db3fe63db',
    messagingSenderId: '1050796442178',
    projectId: 'flutter-trivia-ex',
    storageBucket: 'flutter-trivia-ex.appspot.com',
    androidClientId: '1050796442178-hpo0s5c7bl0oh5n0rc9kn6e4ho4ahjhl.apps.googleusercontent.com',
    iosClientId: '1050796442178-f2sff598197954far4migtu8q8i85oln.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaExpertApp',
  );
}
