name: questions_repository
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  shared_preferences: ^2.0.13
  equatable: ^2.0.2
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


